config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    resources :posts

    root to: "posts#index"
  end

  root 'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/posts', to: 'posts#index'
  resources :posts do
    resources :claims
  end
  
  resources :post_activations, only: [:edit]
  resources :subscriptions, only: [:create, :new]
  resources :subscriptions do
    get :unsubscribe, only: [:unsubscribe]
  end
 
end

app/models/post.rb
class Post < ActiveRecord::Base
  include PgSearch
  include Rakismet::Model
  
  has_many :claims, dependent: :destroy
  attr_accessor :activation_token
  before_save   :downcase_email
  before_create :create_activation_digest
  mount_uploader :picture, PictureUploader
  
  validates :title,  presence: true, length: { maximum: 200 }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }
  validates :description, presence: true
  validate :picture_size

  enum category: [ :request_prayer, :request_help, :offer_prayer, :offer_help ]
  validates :category, inclusion: { in: Post.categories.keys }
  enum status: [ :pending, :active, :met, :expired ]
  validates :status, inclusion: { in: Post.statuses.keys }
  
  # set up search
  scope :status, -> (status) { where status: status }
  scope :category, -> (category) { where category: category }
  
  pg_search_scope :search_for, against: %i(title name description)
  rakismet_attrs :author => :name, :author_email => :email, :content => :description

 
  # Returns true if status is pending
  def pending?
    return status == "pending"
  end
  
  # Returns true if status is met or expired
  def done?
    return status == "met" || status == "expired"
  end

  
  # Activates a post.
  def activate
    update_attribute(:status, :active)
    Subscription.check_subscriptions(self)
  end
  
  # Activates a post.
  def get_class
    cat = ""
    cat = "success" if category == "request_prayer"
    cat = "info" if category == "request_help"
    cat = "warning" if category == "offer_prayer"
    cat = "danger" if category == "offer_help"
    return cat
  end

  # Sends activation email.
  def send_activation_email
    PostMailer.post_activation(self).deliver_now
  end
  
  # Returns the hash digest of the given string.
  def Post.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token.
  def Post.new_token
    SecureRandom.urlsafe_base64
  end

  # Returns true if the given token matches the digest.
  def authenticated?(token)
    digest = send("activation_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  
    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = Post.new_token
      self.activation_digest = Post.digest(activation_token)
    end
    
    # Search terms    
    def self.search(search)
      where("title LIKE ?", "%#{search}%") 
      where("name LIKE ?", "%#{search}%")
      where("description LIKE ?", "%#{search}%")
    end
    
    
  private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Post.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Post.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include ApplicationHelper
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_post, only: [:edit, :update, :destroy]
  before_action :set_categories, only: [:index]

  # GET /posts
  # GET /posts.json
  # def index
  #   if params[:met] == 'true'
  #     @posts = Post.where(status: Post.statuses[:met]).paginate(page: params[:page])
  #   else
  #     @posts = Post.where(status: Post.statuses[:active]).paginate(page: params[:page])
  #   end
  # end
  
def index
  @posts = params[:search].present? ? Post.search_for(params[:search]) : Post.where(nil) 
  @posts = params[:status] == 'met' ? @posts.status(2) : @posts.status(1)
  @posts = @posts.category(params[:category].split("")) if params[:category].present?
  @posts = @posts.paginate(:page => params[:page], :per_page => 10)
end

  # GET /posts/1
  # GET /posts/1.json
  def show
    redirect_to root_url and return unless @post.status == "active" || @post.status == "met"
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.spam?
        format.html { 
          flash[:danger] = "Post NOT created because our robots think it contains spam! If you think this is an error, please e-mail us at info@lovefund.us."
          render :new
        }
      else
        if @post.save
          format.html { 
            @post.send_activation_email
            flash[:success] = "Please check your email to activate your post."
            if @post.category == 'request_help' || 'request_prayer'
              redirect_to controller: 'posts', action: 'index', category: '01'
            elsif @post.category == 'offer_help' || 'offer_prayer'
              redirect_to controller: 'posts', action: 'index', category: '23'
            else
              redirect_to root_url
            end
          }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { flash[:success] = "Post was successfully updated!"; redirect_to @post }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { flash[:success] = "Post was successfully destroyed!"; redirect_to posts_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end
    
    # Confirms a logged-in post.
    def logged_in_post
      unless logged_in? && current_post?(@post)
        flash[:danger] = "You do not have permission for this action."
        redirect_to root_url
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :name, :email, :phone, :street_address, :zip, :description, :description_met, :picture, :facilitated_by_church, :category, :show_phone, :status, :anon_email)
    end
    
    def set_categories
      if params[:category].present?
        @rp = (params[:category].include? '0') ? true : false
        @rh = (params[:category].include? '1') ? true : false
        @op = (params[:category].include? '2') ? true : false
        @oh = (params[:category].include? '3') ? true : false
      else
        redirect_to posts_url('category' => '0123', 'search' => params[:search], 'menu' => params[:menu])
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  
  # Returns the Gravatar for the given email.
  def gravatar_for(claim)
    gravatar_id = Digest::MD5::hexdigest(claim.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?d=identicon"
    image_tag(gravatar_url, size: "50", alt: claim.name, class: "gravatar")
  end
    
  def image_for(post, cls)
    if post.picture.blank?
      return
    else
      image_tag post.picture, :class => cls
    end
  end
    
end

app/views/posts/_form.html.erb
<%= bootstrap_form_for(@post, html: { multipart: true }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  
  <p>
    <% if (params[:category] == '0' ) %>
    Complete this form to request prayer. You may indicate specific things you need prayer for or request prayer for others. The request may be met by anyone willing to pray and will remain open until you close it.
    <% end %>
    <% if (params[:category] == '1' ) %>
    Complete this form to request help. You may indicate specific needs you have, whether service needs around your house, financial needs, etc. You may also request help for others. The request may be met by anyone willing to help and will remain open until you close it.
    <% end %>
    <% if (params[:category] == '2' ) %>
    Complete this form to offer to pray. You may indicate specific days or times you're willing to pray, things you'd specifically like to pray for, etc. The offer may be claimed by anyone needing prayer and will remain open until you close it.
    <% end %>
    <% if (params[:category] == '3' ) %>
    Complete this form to offer your services. You may indicate specific skills you're willing to share, financial or other help you can give. The offer may be claimed by anyone needing help and will remain open until you close it.
    <% end %>
  </p>
  
  <% if (params[:met] ) %>
  <%= f.hidden_field :status, :value => :met %>
  <div class="panel panel-info">
    <div class="panel-heading">
      <h4 class="text-center"> Need or Prayer Met! </h4>
    </div>
    <div class="panel-body">
      <%= f.text_area :description_met, rows: "5", label: "Congratulations! Fill in how your need or prayer was met and then click submit."  %>
    </div>
  </div>
  
  <% end %>

  
  <!--<%= f.select(:category, options_for_select(Post.categories.keys.map {|key| [key.humanize, key]}, f.object.category || Post.categories.keys[params[:category].to_i])) %>-->
  <%= f.hidden_field :category, :value => Post.categories.keys[params[:category].to_i] %>

  <%= f.text_field :title, label: "Title of post" %>
  
  <%= f.text_field :name, label: "Name (Who is posting?)" %>

  <%= f.email_field :email, label: "E-mail (required)", help: "You will have to click a link in your e-mail to activate this post."  %>

  <p><strong>Keep e-mail private</strong></p>
  <%= f.check_box :anon_email, 'data-toggle'=>'toggle', label: " ", checked: true %>
  <p>If selected, will show church e-mail. You will also recieve an e-mail when someone 'claims' your need.</p>
  <%= f.text_field :phone %>
  
  <p><strong>Display phone number on post</strong></p>
  <%= f.check_box :show_phone, 'data-toggle'=>'toggle', label: " " %>

  <%= f.text_field :street_address, label: "Location", help: "(Optional)" %>
  
  <%= f.text_field :zip %>
  
  <%= f.text_area :description, rows: "5"  %>
  
  <!--<%= f.check_box :facilitated_by_church, 'data-toggle'=>'toggle', label: "Facilitated by church. Select if you want all contact to go through the church."  %>-->
  
  
  
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
  <p><small><i>Disclaimer:</i> Lovefund.us is intended to help match people who want to help others with people who could use the help.  This site is not vetted.  The Church in Drive does not have the resources to verify every post.  Use at your own risk.  Please meet in public places and do not give out personal information until you are comfortable doing so and confident that it is safe.</small></p>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<h1><%= (params[:status] == 'met'?'Success Stories': (params[:menu] == 'true') ? 'Search' : (params[:category] == '01') ? 'Get Love' : 'Give Love') %></h1>
<% if(params[:menu] == "true") %> <!-- Search -->
  <div class="row">
    <div class="col-md-2 col-md-offset-2">
      <%= link_to "Request Prayer",
        posts_url(:search => params[:search], :menu => true, :category => (@rp ? params[:category].length > 1 ? params[:category].gsub("0", "") : params[:category] : params[:category]+'0')), 
        class: @rp ? "btn-block btn btn-success" : "btn-block btn btn-default" %>
    </div>
    <div class="col-md-2">
      <%= link_to "Request Help",
        posts_url(:search => params[:search], :menu => true, :category => (@rh ? params[:category].length > 1 ? params[:category].gsub("1", "") : params[:category] : params[:category]+'1')), 
        class: @rh ? "btn-block btn btn-success" : "btn-block btn btn-default" %>
    </div>
    <div class="col-md-2">
      <%= link_to "Offer Prayer",
        posts_url(:search => params[:search], :menu => true, :category => (@op ? params[:category].length > 1 ? params[:category].gsub("2", "") : params[:category] : params[:category]+'2')), 
        class: @op ? "btn btn-success btn-block" : "btn-block btn btn-default" %>
    </div>
    <div class="col-md-2">
      <%= link_to "Offer Help",
        posts_url(:search => params[:search], :menu => true, :category => (@oh ? params[:category].length > 1 ? params[:category].gsub("3", "") : params[:category] : params[:category]+'3')), 
        class: @oh ? "btn btn-success btn-block" : "btn-block btn btn-default" %>
    </div>
  </div>
  
  <div class="row">
    
    <div class="col-md-4 col-md-offset-4">
      <div class="input-group">
        <%= form_tag(posts_path, :method => "get", id: "search-form", :class => "navbar-form") do %>
            <%= hidden_field_tag :category, params[:category] %>
            <%= hidden_field_tag :menu, "true" %>
            <%= text_field_tag :search, params[:search], placeholder: "Search", :class => "form-control" %>
            <span class="input-group-btn">
            <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </span>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<% if(params[:menu] != 'true' && params[:category] == '01' && params[:status] != 'met') %> <!-- Get love -->

  <div class="row">
    <div class="col-sm-offset-2 col-sm-3">
      <p class="text-center">
        <%= link_to "Request<br/>Prayer".html_safe, new_post_url(:category => '0'), :class => 'btn btn-primary btn-block' %>
    </div>
    <div class="col-sm-offset-2 col-sm-3">
      <p class="text-center">
        <%= link_to "Request<br/>Help".html_safe, new_post_url(:category => '1'), :class => 'btn btn-primary btn-block' %>
      </p>
    </div>
  </div>
<% end %>

<% if(params[:menu] != 'true' && params[:category] == '23' && params[:status] != 'met') %> <!-- Give love -->

  <div class="row">
    <div class="col-sm-offset-2 col-sm-3">
      <p class="text-center">
        <%= link_to "Offer<br/>Prayer".html_safe, new_post_url(:category => '2'), :class => 'btn btn-primary btn-block' %>
    </div>
    <div class="col-sm-offset-2 col-sm-3">
      <p class="text-center">
        <%= link_to "Offer<br/>Your Services".html_safe, new_post_url(:category => '3'), :class => 'btn btn-primary btn-block' %>
      </p>
    </div>
  </div>
<% end %>

<div class="text-center padding-bottom">
  
  <% @posts.each do |post| %>
  
<a href="/posts/<%= post.id %>" class="post">
<div class="panel panel-<%= post.get_class %>">
  <div class="panel-heading">
    <h3 class="panel-title"><stong><%= post.category.humanize.upcase %>:</strong> <%= post.title %></h3>
  </div>
  <div class="panel-body">
    <div class="row">
    <% if post.picture.length > 0 %>
      <div class="col-md-2"><%= image_for(post, "img-responsive center-block rounded row-height-2") %></div>
    <% end %>
      <div class="col-md-10 text-left">
        <%= truncate(post.description, length: 250, separator: ' ') %>
        <% if post.description_met.present? %>
        <p class="poster"><i>Thank you message:</i><br><%= truncate(post.description_met, length: 60, separator: ' ') %></p>
        <% end %>
      </div>
    </div> 
  </div>
</div>
</a>


  <% end %>

<%= will_paginate %>

<br>

app/views/posts/new.html.erb
<% provide(:title, 'New') %>
<h1><%= Post.categories.keys[params[:category].to_i].humanize.titleize %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

  </div>
</div>

app/views/posts/show.html.erb
<% provide(:title, @post.title) %>

<article id="post" class="post">


  <div class="row">
  <% if logged_in? && current_post?(@post) %>
    <div class="col-md-12 text-center padding-bottom"> 
      <% if @post.category == "request_prayer" || @post.category == "request_help" %>
          <%= link_to "Need Met!", edit_post_path(@post, :met => true), class: "btn btn-success" %>
      <% end %>
          <%= link_to "Edit", edit_post_path(@post), class: "btn btn-info" %>
          <%= link_to "Delete", @post, 
                      class: "btn btn-danger", 
                      method: :delete, data: { confirm: 'Are you sure?' } %>
      
    </div>
  <% end %>
  </div>
  <div class="row">
    <div class="col-md-12">    
      <%= image_for(@post, "img-responsive center-block thumbnail") %>
      <h1><%= @post.title %></h1>
      <h2>posted by <%= @post.name %></h2>

    </div>
  </div>
  <div class="row">
    <div class="col-md-12">  
    <% if (@post.status == "met") %>    
      <div class="panel panel-info">
        <div class="panel-heading">
          <h4 class="text-center"> Need or Prayer Met! </h4>
        </div>
        <div class="panel-body">
          <%= @post.description_met %>
        </div>
      </div>
    <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-offset-1 col-md-7">
      <div class="row padding-bottom">
        <div class="col-md-2 text-center"><strong>Description</strong></div>
        <div class="col-md-10"><%= @post.description %></div>
      </div>
      
      <% if @post.street_address.length > 1 %>
      <div class="row padding-bottom">
        <div class="col-md-2 text-center"><strong>Location</strong></div>
        <div class="col-md-10"><%= @post.street_address %></div>
      </div>
      <% end %>
      
      <div class="row padding-bottom">
        <div class="col-md-2 text-center"><strong>E-mail</strong></div>
        <div class="col-md-10">
          <%= (@post.anon_email || @post.facilitated_by_church)?"Send e-mail using the \'contact\' button on the right.":@post.email %>
        </div>
      </div>
      
      <% if @post.show_phone %>
        <div class="row padding-bottom">
          <div class="col-md-2 text-center"><strong>Phone</strong></div>
          <div class="col-md-10"><%= @post.phone  %></div>
        </div>
      <% end %>

    </div>

    <div class="col-md-3"> <strong>Share: </strong>
          <ul class="share-buttons">
        <li><a href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Flovefund.us&t=" title="Share on Facebook" target="_blank" onclick="window.open('https://www.facebook.com/sharer/sharer.php?u=' + encodeURIComponent(document.URL) + '&t=' + encodeURIComponent(document.URL)); return false;"><img alt="Share on Facebook" src="../assets/Facebook.svg"></a></li>
        <li><a href="https://twitter.com/intent/tweet?source=http%3A%2F%2Flovefund.us&text=:%20http%3A%2F%2Flovefund.us" target="_blank" title="Tweet" onclick="window.open('https://twitter.com/intent/tweet?text=' + encodeURIComponent(document.title) + ':%20'  + encodeURIComponent(document.URL)); return false;"><img alt="Tweet" src="../assets/Twitter.svg"></a></li>
        <li><a href="https://plus.google.com/share?url=http%3A%2F%2Flovefund.us" target="_blank" title="Share on Google+" onclick="window.open('https://plus.google.com/share?url=' + encodeURIComponent(document.URL)); return false;"><img alt="Share on Google+" src="../assets/Google.svg"></a></li>
        <li><a href="http://pinterest.com/pin/create/button/?url=http%3A%2F%2Flovefund.us&description=" target="_blank" title="Pin it" onclick="window.open('http://pinterest.com/pin/create/button/?url=' + encodeURIComponent(document.URL) + '&description=' +  encodeURIComponent(document.title)); return false;"><img alt="Pin it" src="../assets/Pinterest.svg"></a></li>
        <li><a href="mailto:?subject=&body=:%20http%3A%2F%2Flovefund.us" target="_blank" title="Send email" onclick="window.open('mailto:?subject=' + encodeURIComponent(document.title) + '&body=' +  encodeURIComponent(document.URL)); return false;"><img alt="Send email" src="../assets/Email.svg"></a></li>
      </ul>
      <% if logged_in? && current_post?(@post) %>
        <div class="padding-bottom">
          <%= link_to "Respond", new_post_claim_path(@post, :response => 'true'), remote: true, class: "btn btn-info center-block" %>
        </div>
      <% end %>
      
      <div class="padding-bottom">
        <%= link_to (@post.category == 'offer_help' || @post.category == 'offer_prayer' ?  "Help" : "Claim") + " / Contact", new_post_claim_path(@post), remote: true, class: "btn btn-success center-block" %>
      </div>
        
      <ul class="list-group">
        <% if @post.claims.length > 0 %>
        <li class="list-group-item orange text-center">
          <h4 class="list-group-item-heading">Messages</h4>
        </li>
        <% end %>
      <% @post.claims.each do |claim| %>
        <% if !claim.private %>
          <li class="<%= claim.email == @post.email ? "list-group-item poster" : "list-group-item" %>">
            <div class="row">
              <div class="col-xs-3">
                <%= gravatar_for(claim) %>
              </div>
              <div class="col-xs-9">
                <% if claim.email == @post.email %>
                  <i class="list-group-item-heading">Response from <%= claim.name %>:</i>
                <% else %>
                  <h4 class="list-group-item-heading"><%= claim.name %></h4>
                <% end %>
                <p class="list-group-item-text"><%= claim.note %></p>
                <% if logged_in? && current_post?(@post) %>
                    <%= link_to "Delete", post_claim_path(@post, claim), 
                        class: "", 
                        method: :delete, data: { confirm: 'Are you sure?' } %>
                <% end %>
              </div>
    
            </div>
          </li>
        <% end %>
      <% end %>
      </ul>
    </div>

  </div>



  


<div class="row">
  <div class="col-md-12 text-center"> 
  
  <%= link_to 'Back', posts_path, class: "btn btn-primary" %>
  </div>
</div>

</article>