config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    resources :posts

    root to: "posts#index"
  end

  root 'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/posts', to: 'posts#index'
  resources :posts do
    resources :claims
  end
  
  resources :post_activations, only: [:edit]
  resources :subscriptions, only: [:create, :new]
  resources :subscriptions do
    get :unsubscribe, only: [:unsubscribe]
  end
 
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <!--<div class="center">-->
  <!--<small>-->
  <!--  Created by <a href="http://fruitful.software">Beau Carnes</a>.-->
  <!--</small>-->
  <!--</div>-->
</footer>

app/views/layouts/_header.html.erb
<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" 
          data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-left navbar-brand logo-padding" href="/">
        <%= image_tag("lovefundlogosmall.png") %>
      </a>
    </div>
    
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Get Love",   posts_url(:category => '01') %></li>
        <li><%= link_to "Give Love",   posts_url(:category => '23') %></li>      
        <li><%= link_to "Search",   posts_url( :menu => true ) %></li>
        <li><%= link_to "Success Stories", 
              posts_url(:search => params[:search], :category => '01', :status => 'met') %>
        </li>
        <!--<li><%= link_to "Notifications", new_subscription_path, method: :get %></li>-->
        <li><%= link_to "About",   about_path %></li>
        <!--<li><%= button_to 'New Post', new_post_path, class: "btn navbar-btn btn-info", method: :get %></li>-->
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>
<% if current_page?(controller: 'posts', action: 'index') %>
<div class="notification-nav text-center">
  <%= link_to "Stay Connected: get email notifications from lovefund", new_subscription_path, method: :get %>
</div>
<% end %>

app/views/layouts/_homeheader.html.erb
<div class="hero-unit">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= image_tag("lovefund.png", class: "img-responsive padding-top center-block") %>
      <h2>lovefund.us is an online portal for sharing and meeting prayer requests, and financial or service needs, for ourselves and others.</h2>
      <div class="row">
        <div class="col-sm-6">
          <p class="text-center">
            <%= link_to "GET<br/>some love".html_safe, posts_url(:category => '01'), :class => 'btn btn-primary btn-large large-text' %>
        </div>
        <div class="col-sm-6">
          <p class="text-center">
            <%= link_to "GIVE<br/>some love".html_safe, posts_url(:category => '23'), :class => 'btn btn-primary btn-large large-text' %>
          </p>
        </div>
      </div>
      
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% if current_page?(controller: 'static_pages', action: 'home') %>
      <%= render 'layouts/homeheader' %>
    <% end%>
    <div class="container main-container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
      
      <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>